# Generated by Django 3.0.8 on 2020-07-03 19:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(regex='^\\d{4}$')])),
                ('session', models.CharField(choices=[('W', 'Winter'), ('S', 'Summer')], max_length=1)),
                ('subject', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{4}$')])),
                ('number', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(regex='^[A-Z0-9]{3,4}$')])),
                ('section', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(regex='^[A-Z0-9]{3,5}$')])),
                ('last_open', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['year', 'session', 'subject', 'number', 'section'],
                'unique_together': {('year', 'session', 'subject', 'number', 'section')},
            },
        ),
        migrations.CreateModel(
            name='CourseTuple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restricted', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
            options={
                'ordering': ['course', 'restricted'],
                'unique_together': {('restricted', 'course')},
            },
        ),
    ]
