# Generated by Django 3.0.8 on 2020-07-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='last_open',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
