# Generated by Django 3.0.8 on 2020-07-12 04:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200705_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{2,4}$')]),
        ),
    ]
