# Generated by Django 3.0.8 on 2020-07-16 03:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200712_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(regex='^20\\d{2}$')]),
        ),
    ]
