# Generated by Django 3.0.8 on 2020-07-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200716_0445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['campus', 'year', 'session', 'subject', 'number', 'section']},
        ),
        migrations.AddField(
            model_name='course',
            name='campus',
            field=models.CharField(choices=[('UBC', 'UBC Vancouver'), ('UBCO', 'UBC Okanagan')], default='UBC', max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('campus', 'year', 'session', 'subject', 'number', 'section')},
        ),
    ]
